### ISSUE TITLE
Add includepkgs option to config options

### ISSUE THREAD

**Issue by abtreece** [jrwesolo/yumsync#17]
Considering switching to yumsync from pakrat, but currently use the includepkgs option to pakrat. Is that an option that could be added to the config options for yumsync?

**Comment by jrwesolo** [comment]
@abtreece I'll take a look this week and see what can be improved! Thanks for the suggestion.

**Comment by jrwesolo** [comment]
@abtreece I've released version 1.1.0 of yumsync with support for includepkgs and excludepkgs. Here is an example of a repos.yml file that uses the new features:

```yaml
---
centos/7/extras/x86_64:
  mirrorlist: 'http://mirrorlist.centos.org/?release=7&repo=extras&arch=x86_64'
  gpgkey: 'http://mirror.centos.org/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7'
  includepkgs: 'docker*'
  excludepkgs: 'docker-latest*'
```

Those two settings can be provided either as a string or an array. Let me know if you have any more questions about migrating over!
